version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    owner: "ec2-user"
    mode: 755

hooks:
  AfterInstall:
    - location: /home/ec2-user/glass-bottle/scripts/deploy.sh
      timeout: 60
      runas: root