version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/glass-bottle-app
permissions:
  - object: /home/ubuntu/glass-bottle-app
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root