version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /home/ec2-user
    owner: "glass-bottle-code-deploy"
    group: "glass-bottle-group"
    mode: 775

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root